url: https://dexterski007.github.io
baseurl: /The-Maze-Project/

# Site settings
title: The Maze Project
email: mbouj007@gmail.com
description: "This project is the culmination of ALX SE Foundations Journey, it is a maze game written in C, using SDL2 and raycasting, featuring a level editor, an amazing layout, responsive commands, and customized textures. The game is a first-person perspective game, where the player navigates through a maze, with the goal of reaching the end of the maze"


# Team names, titles and social links
people:
- name: dexterski007
  pic: 1
  position: Lead Developper
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/mohamed-boujelfa-128b0a287/
  - title: github
    url: https://www.github.com/dexterski007

# Build settings
markdown: kramdown
permalink: pretty